# Generated by Django 4.2.6 on 2023-11-30 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='the description of the item')),
                ('details', models.TextField(blank=True, default='more details about picking up, or the number to call', null=True)),
                ('location', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=30)),
                ('is_available', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='item_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ('title',),
            },
        ),
    ]
